### ISSUE TITLE
Add support for Gnome 3.36

### ISSUE THREAD

**Issue by lenuswalker** [lvitals/panel-indicators#18]
Extension does not work on gnome 3.36 beta.

**Comment by mohegan** [comment]
With Gnome 3.36, the extension doen't work for me too.
I have this error : "Main.panel.statusArea.dateMenu._messageList._removeSection is not a function"

**Comment by leokaplan** [comment]
On 3.28.2 I get 
>`this.add_child` is not a function

**Comment by probonopd** [comment]
GNOME still isn't ABI stable, even in X.28.2?

**Comment by TheBlackKoala** [comment]
Has anyone found any fixes?

**Comment by TheBlackKoala** [comment]
@mohegan could i get you to check if this works for you as well? I have changed the indicators folder in the extension to what is in this zip-file. The calendar doesn't work correctly but all the others seem fine to me.
If this works for you as well i will clean it up and make a PR.
[indicators.zip](https://github.com/lvitals/panel-indicators/files/4492234/indicators.zip)

**Comment by TheBlackKoala** [comment]
There should be support for 3.36 in #19 - if you have any problems let me know. (Disclaimer - i am not the maintainer on this project i just found a way to fix the problems)

**Comment by hlinkam** [comment]
Tried https://extensions.gnome.org/extension/1526/notification-centerselenium-h/ but it doesn't work for me. Yes, notification center part is working - it can remove notification from calendar and shows separate notification icon but it doesn't separate system indicators like this extension did.

**Comment by hlinkam** [comment]
@TheBlackKoala tried with zip you attached here and its working, many thanks!

**Comment by TheBlackKoala** [comment]
@hlinkam kan you give me a readout of errors from your journalctl?

**Comment by TheBlackKoala** [comment]
@hlinkam The notification-center is only for the notification-center. i just used how their code worked in my PR - could i get you to download the version from: https://github.com/TheBlackKoala/panel-indicators and see if that works?

**Comment by hlinkam** [comment]
@TheBlackKoala it works as well but there seems to be something wrong. I am using dash to panel and when I am playing with its settings, system indicators disappears completely and I am unable to either turn off or on this extension. Removed it completely, rebuilded, restarted session and system indicators are there again. 
Same goes for when I disable and enable extension, system indicators disappears and have to go through rebuild process again. Same results on wayland and xorg.

**Comment by TheBlackKoala** [comment]
@hlinkam can you give me a read-out of your system? I don't use dash-to-panel myself, but there are a few errors in the system currently that i haven't been able to work out.

**Comment by hlinkam** [comment]
@TheBlackKoala what do you mean by read-out of my system?

**Comment by TheBlackKoala** [comment]
@hlinkam On arch i'd use `journalctl -r --grep="panel-indicator"` to get the system-errors connected to panel-indicator, so something similar from your system

**Comment by TheBlackKoala** [comment]
@hlinkam also first could i get you to go to extensions.js and move the creation of variables around lines 63-70 so that `notification = new NotificationIndicator();` is before `calendar = new CalendarIndicator();`? See if that works.

**Comment by mohegan** [comment]
@TheBlackKoala I have tested your files but it doesn't work. See the log :
[log.pdf](https://github.com/lvitals/panel-indicators/files/4492846/log.pdf)

**Comment by mohegan** [comment]
> @hlinkam also first could i get you to go to extensions.js and move the creation of variables around lines 63-70 so that `notification = new NotificationIndicator();` is before `calendar = new CalendarIndicator();`? See if that works.

I have tested that too. Don't work...

**Comment by TheBlackKoala** [comment]
@mohegan could i get you to test my PR? https://github.com/TheBlackKoala/panel-indicators
And what other extensions do you have installed?
What is the behaviour when it doesn't work? Have all the icons disappeared or is something else happening?

**Comment by TheBlackKoala** [comment]
I have just updated my repository, it does not throw any more errors on my system, though i suspect that there may be things that i have just commented out that may be needed for things that i don't use.

Please let me know whether it works or not.
If it does not work please try restarting and if it still doesn't work then attach a system-log for me.

**Comment by hlinkam** [comment]
@TheBlackKoala I get this after your last commit in your repo.
[panel-indicator.txt](https://github.com/lvitals/panel-indicators/files/4493241/panel-indicator.txt)

**Comment by TheBlackKoala** [comment]
@hlinkam try to restart your shell - alt+f2 then "r" and enter.
Otherwise please send me your /home/martin/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/volume.js

**Comment by hlinkam** [comment]
@TheBlackKoala I may be doing something wrong during the build maybe? Here is what I do and what happens.
Run these two:
```
meson --prefix=$HOME/.local/ --localedir=share/gnome-shell/extensions/panel-indicators@leavitals/locale .build
ninja -C .build install
```
After that I restart my shell. Extension work. Super is that now I can adjust dash-to-panel settings, turn system-indicators on and off as I want and everything works.
Extension app says that extension will be update upon next login. After logout and back login - extension stops working. I assume that this update messes it up.

**Comment by mohegan** [comment]
Your git repository work for me ! Just thew bugs :

1. If I disable notification icon, I can't view the notifications with the calendar. 
2. I can't view the calendar events at all (in notification area or in calendar)

Good work !

**Comment by TheBlackKoala** [comment]
Good to hear guys! I have noted it preliminary because it is just a quick and dirty fix but it works for now.
I will try to look into the problem with notifications and calender events.

I have a feeling that it might be connected to this error: `JS ERROR: Error: No signal 'count-updated' on object 'Gjs_ui_notificationDaemon_FdoNotificationDaemonSource'`

**Comment by BjoernDaase** [comment]
@TheBlackKoala Thanks a lot, your fork works already very well!  

I found a few things that are not quite right yet (you might or might not know yet):
1. The margins in the (right and bottom) calendar section are off
![image](https://user-images.githubusercontent.com/24682367/79602277-7f05a380-80ea-11ea-9744-837d6bce4a70.png)
2. If "Do Not Disturb" mode is checked, the icon in the top panel is not striked out
3. There are quite a lot of `clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed` errors in the log
4. There also tons of warning that `Usage of object.actor is deprecated` which should not be to big of a problem for now

**Comment by TheBlackKoala** [comment]
@BjoernDaase
1 Yes the whole notification/calendar area is wonky but i can't find anyone who has done their handling in the same way as this extension so i fear that we may have to wait for the maintainer @lvitals to have a look. Otherwise the zip-file i uploaded in this thread should handle that in that it lets you see everything in calendar and just notifications in notifications.
2 - that would need a new icon and handling to go with that
3 - i will take a look at that time permitting.
4 I have not seen any of the errors in my log can you send me a log with a few of those in it?
5 i think you may be looking at old logs because i definitely removed all the deprecated warnings i saw. - Otherwise it is just to remove the ".actor" part on the line that is referenced in the log.

In general i think many of these errors deserve their own issue-thread but as i don't have the time to work all the kinks out and find the weird solution, i will work when i am able but i really hope that lvitals will be able to return to the extension.
Anyone else who wants to look into it should get some hints from my PR #19 .

**Comment by mohegan** [comment]
For the notification/calendar, maybe you can just remove or disable the modified calendar and notification indicators. So, we can just have the original calendar/notification indicator (in one place, not separated).

I think it can be much easier for now.

**Comment by TheBlackKoala** [comment]
There is unfortunately no easy way to get the calendar to work. I have tried not removing sections etc but it still doesn't work.
I might look into having notification-center just doing the whole calendar/notification area but that still requires quite a bit of change.

**Comment by BjoernDaase** [comment]
@TheBlackKoala   
1. Alright, make sense. Besides that, I did not use your zip and instead used your repo (https://github.com/TheBlackKoala/panel-indicators)
2. That icon exists in default GNOME 3.36. You can see it when toggling the DND switch (without the panel-indicator extension)
3. :+1: 
4. Sure, here is a full log of enabling and disabling the panel-indicator extension (in a running GNOME session without any interaction with menus: [journal.log](https://github.com/lvitals/panel-indicators/files/4502394/journal.log)
5. So the branch in your Github is not up to date? Or what am I doing wrong?

No worried at all, I just wanted to let you know :)

**Comment by TheBlackKoala** [comment]
@BjoernDaase thank you for your log - i have removed all the deprecated warnings i saw in your log and updated my fork. I never disabled the extension so they came from the destroy functions. I will have to look further into the clutter_actor_*_child assertions so see if they are coming from this extension and what to do about it.

**Comment by niquedegraaff** [comment]
@TheBlackKoala I also have dash to panel and experience the same issues. I used your repository these are the errors I get.

    Extension panel-indicators@leavitals: TypeError: obj is undefined
        _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/volume.js:44:9
        enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:65:14

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
        _init@/usr/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
        enable@/usr/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
         _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
         enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
        _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
        enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
        _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
        enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
         _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
         enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

    Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
         _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:46:9
         enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15`

**Comment by TheBlackKoala** [comment]
@niquedegraaff I have just tried to address the error in your post (the lastest commit to my fork) but i did not get the same errors myself with dash-to-panel. Can you tell me if they help on your end?

**Comment by BjoernDaase** [comment]
@TheBlackKoala Things definitely look better. Anyway, there are still some warnings (also deprecated actor warnings) in there so if you want to have a look into it, here is the log (freshly pulled your repo minutes ago): [log.txt](https://github.com/lvitals/panel-indicators/files/4514452/log.txt)

Ah, and after disabling the extension again the calendar panel is flipped.While this looks fancy I do not think this is intended :P

**Comment by BjoernDaase** [comment]
Ah, and while you are on it: You might want to have a look into issues like https://github.com/lvitals/panel-indicators/issues, for some reason the orange indicators (for screen sharing, recording...) are not shown anymore.

**Comment by TheBlackKoala** [comment]
@BjoernDaase i have handled the deprecated warnings from your log.

**Comment by niquedegraaff** [comment]
@TheBlackKoala I've updated it, and there seems to be one error  left regarding the remove_actor function inside network.js. 

    JS ERROR: Extension panel-indicators@leavitals: TypeError: this._location.remove_actor is not a function
        _init@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/network.js:47:13
        enable@/home/nique/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:63:15

**Comment by BjoernDaase** [comment]
They are gone indeed. This is what remains: [log.txt](https://github.com/lvitals/panel-indicators/files/4517551/log.txt)

**Comment by TheBlackKoala** [comment]
Okay so i have for now i am removing all support for the calendar.
Considering that notification center already supports it and that they do things in a manner quite seperate from what panel-indicators does.
I am currently trying to remove everything calendar or notification but it may take some time. For now it works with the regular gnome calendar/notification, but not extensions for it.

**Comment by mohegan** [comment]
> Okay so i have for now i am removing all support for the calendar.
> Considering that notification center already supports it and that they do things in a manner quite seperate from what panel-indicators does.
> I am currently trying to remove everything calendar or notification but it may take some time. For now it works with the regular gnome calendar/notification, but not extensions for it.

Good to know. Thanks !

**Comment by lenuswalker** [comment]
Support for 3.36 should be completed with my pull request. #20

**Comment by patricklibert** [comment]
This doesn't work on Ubuntu 20.04.

The error I get:

`JS ERROR: Extension panel-indicators@leavitals: TypeError: Main.panel.statusArea.dateMenu._messageList._removeSection is not a function
                                                      _init@/home/redman/.local/share/gnome-shell/extensions/panel-indicators@leavitals/indicators/volume.js:44:53
                                                      wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                      enable@/home/redman/.local/share/gnome-shell/extensions/panel-indicators@leavitals/extension.js:65:14
                                                      _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                                      loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                                      _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
                                                      collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                                      _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
                                                      _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:608:18
                                                      _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
                                                      init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                                      _initializeUI@resource:///org/gnome/shell/ui/main.js:257:22
                                                      start@resource:///org/gnome/shell/ui/main.js:146:5
                                                      @<main>:1:47
`

**Comment by iyyel** [comment]
I get the same error as @patricklibert on 3.38, among `this._bluetooth._getNDevices is not a function` and more.
